import type { MarketStatus } from "@/lib/domain/types";

/**
 * Status never relies on colour alone — each state carries its own word, which
 * is what PRD §10.3 requires for accessibility.
 */
const STYLES: Record<MarketStatus, { label: string; className: string }> = {
  trading:  { label: "Trading",    className: "badge-good" },
  upcoming: { label: "Opens soon", className: "badge-neutral" },
  locked:   { label: "Locked",     className: "badge-warn" },
  settling: { label: "Settling",   className: "badge-warn" },
  resolved: { label: "Resolved",   className: "badge-neutral" },
  voided:   { label: "Voided",     className: "badge-danger" },
};

export function StatusPill({ status, className = "" }: { status: MarketStatus; className?: string }) {
  const s = STYLES[status];
  return (
    <span className={`badge ${s.className} ${className}`}>
      {status === "trading" && <span className="live-dot h-1.5 w-1.5 rounded-full bg-good" aria-hidden />}
      {s.label}
    </span>
  );
}

/**
 * Provenance, for a contract the local simulation generated during an indexer
 * outage. It lives beside {@link StatusPill} because it always qualifies one:
 * a contract can read "Trading" and still exist nowhere on Somnia.
 */
export function SimulatedPill({ className = "" }: { className?: string }) {
  return (
    <span
      title="Generated by the local fallback. This contract does not exist on Somnia and cannot take an order."
      className={`badge badge-danger ${className}`}
    >
      Simulated
    </span>
  );
}
